name: google_maps_place_picker_mb
description: A Flutter plugin which provides 'Picking Place' using Google Maps
  widget. (MB version)
version: 3.0.0
homepage: https://github.com/martin-braun/google_maps_place_picker_mb

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  google_api_headers: ^3.7.1
  google_maps_flutter: ^2.2.2
  google_maps_webservice:
    path: C:\projects\flutter\google_maps_webservice
  http: ^0.13.5
  location: ^5.0.3
  provider: ^6.0.5
  tuple: ^2.0.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null

false_secrets:
 - /example/lib/keys.dart
 - /example/android/app/src/main/AndroidManifest.xml
 - /example/ios/Runner/AppDelegate.swift
